import{a as n,S as p,i as c}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const g="52329840-3cdbe1d1ca17a86ceb553d9b5";n.defaults.baseURL="https://pixabay.com/api/";n.defaults.params={};n.defaults.params.key=g;function h(a){return n.get("",{params:{q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:21}}).then(r=>r.data.hits)}const f=document.querySelector(".gallery"),l=document.querySelector(".loader"),y=new p(".gallery-item a",{captionsData:"alt",captionDelay:250});function L(a){const r=a.map(({tags:s,likes:i=0,views:e=0,comments:t=0,downloads:o=0,webformatURL:m,largeImageURL:d})=>`
        <li class="gallery-item">
          <a class="gallery-origin-img" href="${d}">
            <img class="gallery-prewiew-img" src="${m}" alt="${s}" width="360" height="152"/>
            </a>
            <div class="gallery-info-wrapper">
              <h4 class="gallery-info-item">Likes<span>${i}<span></h4>
              <h4 class="gallery-info-item">Views<span>${e}<span></h4>
              <h4 class="gallery-info-item">Comments<span>${t}<span></h4>
              <h4 class="gallery-info-item">Downloads<span>${o}<span></h4>
            </div>
        </li>
        `).join("");f.innerHTML=r,y.refresh()}function u(){f.innerHTML=""}function w(){l.classList.remove("hide")}function b(){l.classList.contains("hide")||l.classList.add("hide")}const S=document.querySelector(".form");S.addEventListener("submit",v);function v(a){a.preventDefault();const r=String(a.target.elements["search-text"].value.trim());if(!r)return c.error({icon:"",position:"topRight",message:`Pleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaase, do not try to enter "${r}", i know how to use trim()!`,timeout:5e3,progressBar:!1,close:!1,messageColor:"white"},u());u(),w(),h(r).then(s=>{if(!s.length)throw new Error("Sorry, there are no images matching your search query. Please try again!");L(s)}).catch(s=>(console.log("error"),c.error({icon:"",position:"topRight",message:s.message,timeout:5e3,progressBar:!1,close:!1,messageColor:"white"}))).finally(()=>b(),a.target.reset())}
//# sourceMappingURL=index.js.map
