import{a as n,S as p,i as l}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const d="52329840-3cdbe1d1ca17a86ceb553d9b5";n.defaults.baseURL="https://pixabay.com/api/";n.defaults.params={};n.defaults.params.key=d;function h(s){return n.get("",{params:{q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:21}}).then(r=>r.data.hits)}const f=document.querySelector(".gallery"),c=document.querySelector(".loader"),y=new p(".gallery-item a",{captionsData:"alt",captionDelay:250});function L(s){const r=s.map(({tags:a,likes:i=0,views:e=0,comments:t=0,downloads:o=0,webformatURL:m,largeImageURL:g})=>`
        <li class="gallery-item">
          <a class="gallery-origin-img" href="${g}">
            <img class="gallery-prewiew-img" src="${m}" alt="${a}" width="360" height="152"/>
            </a>
            <div class="gallery-info-wrapper">
              <h4 class="gallery-info-item">Likes<span>${i}<span></h4>
              <h4 class="gallery-info-item">Views<span>${e}<span></h4>
              <h4 class="gallery-info-item">Comments<span>${t}<span></h4>
              <h4 class="gallery-info-item">Downloads<span>${o}<span></h4>
            </div>
        </li>
        `).join("");f.innerHTML=r,y.refresh()}function u(){f.innerHTML=""}function w(){c.classList.remove("hide")}function b(){c.classList.contains("hide")||c.classList.add("hide")}const S=document.querySelector(".form");S.addEventListener("submit",q);function q(s){s.preventDefault();const r=String(s.target.elements["search-text"].value.trim());if(!r)return l.error({icon:"",position:"topRight",message:"Please, enter your search query!",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"});w(),h(r).then(a=>{if(!a.length)return u(),l.info({icon:"",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"});L(a),s.target.reset()}).catch(a=>(u(),l.error({icon:"",position:"topRight",message:a.message||"Something went wrong. Please try again later.",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"}))).finally(()=>{b()})}
//# sourceMappingURL=index.js.map
